export const AppConstants = {
  token: "token",
  dateFormat: "YYYY-MM-DD",
  regex: {
    email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  },
};

const countriesMap = new Map([
  ["South Georgia", "South Georgia"],
  ["Grenada", "Grenada"],
  ["Switzerland", "Switzerland"],
  ["Sierra Leone", "Sierra Leone"],
  ["Hungary", "Hungary"],
  ["Taiwan", "Taiwan"],
  ["Wallis and Futuna", "Wallis and Futuna"],
  ["Barbados", "Barbados"],
  ["Pitcairn Islands", "Pitcairn Islands"],
  ["Ivory Coast", "Ivory Coast"],
  ["Tunisia", "Tunisia"],
  ["Italy", "Italy"],
  ["Benin", "Benin"],
  ["Indonesia", "Indonesia"],
  ["Cape Verde", "Cape Verde"],
  ["Saint Kitts and Nevis", "Saint Kitts and Nevis"],
  ["Laos", "Laos"],
  ["Caribbean Netherlands", "Caribbean Netherlands"],
  ["Uganda", "Uganda"],
  ["Andorra", "Andorra"],
  ["Burundi", "Burundi"],
  ["South Africa", "South Africa"],
  ["France", "France"],
  ["Libya", "Libya"],
  ["Mexico", "Mexico"],
  ["Gabon", "Gabon"],
  ["Northern Mariana Islands", "Northern Mariana Islands"],
  ["North Macedonia", "North Macedonia"],
  ["China", "China"],
  ["Yemen", "Yemen"],
  ["Saint Barthélemy", "Saint Barthélemy"],
  ["Guernsey", "Guernsey"],
  ["Solomon Islands", "Solomon Islands"],
  ["Svalbard and Jan Mayen", "Svalbard and Jan Mayen"],
  ["Faroe Islands", "Faroe Islands"],
  ["Uzbekistan", "Uzbekistan"],
  ["Egypt", "Egypt"],
  ["Senegal", "Senegal"],
  ["Sri Lanka", "Sri Lanka"],
  ["Palestine", "Palestine"],
  ["Bangladesh", "Bangladesh"],
  ["Peru", "Peru"],
  ["Singapore", "Singapore"],
  ["Turkey", "Turkey"],
  ["Afghanistan", "Afghanistan"],
  ["Aruba", "Aruba"],
  ["Cook Islands", "Cook Islands"],
  ["United Kingdom", "United Kingdom"],
  ["Zambia", "Zambia"],
  ["Finland", "Finland"],
  ["Niger", "Niger"],
  ["Christmas Island", "Christmas Island"],
  ["Tokelau", "Tokelau"],
  ["Guinea-Bissau", "Guinea-Bissau"],
  ["Azerbaijan", "Azerbaijan"],
  ["Réunion", "Réunion"],
  ["Djibouti", "Djibouti"],
  ["North Korea", "North Korea"],
  ["Mauritius", "Mauritius"],
  ["Montserrat", "Montserrat"],
  ["United States Virgin Islands", "United States Virgin Islands"],
  ["Colombia", "Colombia"],
  ["Greece", "Greece"],
  ["Croatia", "Croatia"],
  ["Morocco", "Morocco"],
  ["Algeria", "Algeria"],
  ["Antarctica", "Antarctica"],
  ["Netherlands", "Netherlands"],
  ["Sudan", "Sudan"],
  ["Fiji", "Fiji"],
  ["Liechtenstein", "Liechtenstein"],
  ["Nepal", "Nepal"],
  ["Puerto Rico", "Puerto Rico"],
  ["Georgia", "Georgia"],
  ["Pakistan", "Pakistan"],
  ["Monaco", "Monaco"],
  ["Botswana", "Botswana"],
  ["Lebanon", "Lebanon"],
  ["Papua New Guinea", "Papua New Guinea"],
  ["Mayotte", "Mayotte"],
  ["Dominican Republic", "Dominican Republic"],
  ["Norfolk Island", "Norfolk Island"],
  ["Bouvet Island", "Bouvet Island"],
  ["Qatar", "Qatar"],
  ["Madagascar", "Madagascar"],
  ["India", "India"],
  ["Syria", "Syria"],
  ["Montenegro", "Montenegro"],
  ["Eswatini", "Eswatini"],
  ["Paraguay", "Paraguay"],
  ["El Salvador", "El Salvador"],
  ["Ukraine", "Ukraine"],
  ["Isle of Man", "Isle of Man"],
  ["Namibia", "Namibia"],
  ["United Arab Emirates", "United Arab Emirates"],
  ["Bulgaria", "Bulgaria"],
  ["Greenland", "Greenland"],
  ["Germany", "Germany"],
  ["Cambodia", "Cambodia"],
  ["Iraq", "Iraq"],
  [
    "French Southern and Antarctic Lands",
    "French Southern and Antarctic Lands",
  ],
  ["Sweden", "Sweden"],
  ["Cuba", "Cuba"],
  ["Kyrgyzstan", "Kyrgyzstan"],
  ["Russia", "Russia"],
  ["Malaysia", "Malaysia"],
  ["São Tomé and Príncipe", "São Tomé and Príncipe"],
  ["Cyprus", "Cyprus"],
  ["Canada", "Canada"],
  ["Malawi", "Malawi"],
  ["Saudi Arabia", "Saudi Arabia"],
  ["Bosnia and Herzegovina", "Bosnia and Herzegovina"],
  ["Ethiopia", "Ethiopia"],
  ["Spain", "Spain"],
  ["Slovenia", "Slovenia"],
  ["Oman", "Oman"],
  ["Saint Pierre and Miquelon", "Saint Pierre and Miquelon"],
  ["Macau", "Macau"],
  ["San Marino", "San Marino"],
  ["Lesotho", "Lesotho"],
  ["Marshall Islands", "Marshall Islands"],
  ["Sint Maarten", "Sint Maarten"],
  ["Iceland", "Iceland"],
  ["Luxembourg", "Luxembourg"],
  ["Argentina", "Argentina"],
  ["Turks and Caicos Islands", "Turks and Caicos Islands"],
  ["Nauru", "Nauru"],
  ["Cocos (Keeling) Islands", "Cocos (Keeling) Islands"],
  ["Western Sahara", "Western Sahara"],
  ["Dominica", "Dominica"],
  ["Costa Rica", "Costa Rica"],
  ["Australia", "Australia"],
  ["Thailand", "Thailand"],
  ["Haiti", "Haiti"],
  ["Tuvalu", "Tuvalu"],
  ["Honduras", "Honduras"],
  ["Equatorial Guinea", "Equatorial Guinea"],
  ["Saint Lucia", "Saint Lucia"],
  ["French Polynesia", "French Polynesia"],
  ["Belarus", "Belarus"],
  ["Latvia", "Latvia"],
  ["Palau", "Palau"],
  ["Guadeloupe", "Guadeloupe"],
  ["Philippines", "Philippines"],
  ["Gibraltar", "Gibraltar"],
  ["Denmark", "Denmark"],
  ["Cameroon", "Cameroon"],
  ["Guinea", "Guinea"],
  ["Bahrain", "Bahrain"],
  ["Suriname", "Suriname"],
  ["DR Congo", "DR Congo"],
  ["Somalia", "Somalia"],
  ["Czechia", "Czechia"],
  ["New Caledonia", "New Caledonia"],
  ["Vanuatu", "Vanuatu"],
  [
    "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Helena, Ascension and Tristan da Cunha",
  ],
  ["Togo", "Togo"],
  ["British Virgin Islands", "British Virgin Islands"],
  ["Kenya", "Kenya"],
  ["Niue", "Niue"],
  ["Heard Island and McDonald Islands", "Heard Island and McDonald Islands"],
  ["Rwanda", "Rwanda"],
  ["Estonia", "Estonia"],
  ["Romania", "Romania"],
  ["Trinidad and Tobago", "Trinidad and Tobago"],
  ["Guyana", "Guyana"],
  ["Timor-Leste", "Timor-Leste"],
  ["Vietnam", "Vietnam"],
  ["Uruguay", "Uruguay"],
  ["Vatican City", "Vatican City"],
  ["Hong Kong", "Hong Kong"],
  ["Austria", "Austria"],
  ["Antigua and Barbuda", "Antigua and Barbuda"],
  ["Turkmenistan", "Turkmenistan"],
  ["Mozambique", "Mozambique"],
  ["Panama", "Panama"],
  ["Micronesia", "Micronesia"],
  ["Ireland", "Ireland"],
  ["Curaçao", "Curaçao"],
  ["French Guiana", "French Guiana"],
  ["Norway", "Norway"],
  ["Åland Islands", "Åland Islands"],
  ["Central African Republic", "Central African Republic"],
  ["Burkina Faso", "Burkina Faso"],
  ["Eritrea", "Eritrea"],
  ["Tanzania", "Tanzania"],
  ["South Korea", "South Korea"],
  ["Jordan", "Jordan"],
  ["Mauritania", "Mauritania"],
  ["Lithuania", "Lithuania"],
  [
    "United States Minor Outlying Islands",
    "United States Minor Outlying Islands",
  ],
  ["Slovakia", "Slovakia"],
  ["Angola", "Angola"],
  ["Kazakhstan", "Kazakhstan"],
  ["Moldova", "Moldova"],
  ["Mali", "Mali"],
  ["Falkland Islands", "Falkland Islands"],
  ["Armenia", "Armenia"],
  ["Samoa", "Samoa"],
  ["Jersey", "Jersey"],
  ["Japan", "Japan"],
  ["Bolivia", "Bolivia"],
  ["Chile", "Chile"],
  ["United States", "United States"],
  ["Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"],
  ["Bermuda", "Bermuda"],
  ["Seychelles", "Seychelles"],
  ["British Indian Ocean Territory", "British Indian Ocean Territory"],
  ["Guatemala", "Guatemala"],
  ["Ecuador", "Ecuador"],
  ["Martinique", "Martinique"],
  ["Tajikistan", "Tajikistan"],
  ["Malta", "Malta"],
  ["Gambia", "Gambia"],
  ["Nigeria", "Nigeria"],
  ["Bahamas", "Bahamas"],
  ["Kosovo", "Kosovo"],
  ["Kuwait", "Kuwait"],
  ["Maldives", "Maldives"],
  ["South Sudan", "South Sudan"],
  ["Iran", "Iran"],
  ["Albania", "Albania"],
  ["Brazil", "Brazil"],
  ["Serbia", "Serbia"],
  ["Belize", "Belize"],
  ["Myanmar", "Myanmar"],
  ["Bhutan", "Bhutan"],
  ["Venezuela", "Venezuela"],
  ["Liberia", "Liberia"],
  ["Jamaica", "Jamaica"],
  ["Poland", "Poland"],
  ["Cayman Islands", "Cayman Islands"],
  ["Brunei", "Brunei"],
  ["Comoros", "Comoros"],
  ["Guam", "Guam"],
  ["Tonga", "Tonga"],
  ["Kiribati", "Kiribati"],
  ["Ghana", "Ghana"],
  ["Chad", "Chad"],
  ["Zimbabwe", "Zimbabwe"],
  ["Saint Martin", "Saint Martin"],
  ["Mongolia", "Mongolia"],
  ["Portugal", "Portugal"],
  ["American Samoa", "American Samoa"],
  ["Republic of the Congo", "Republic of the Congo"],
  ["Belgium", "Belgium"],
  ["Israel", "Israel"],
  ["New Zealand", "New Zealand"],
  ["Nicaragua", "Nicaragua"],
  ["Anguilla", "Anguilla"],
]);

export const countriesArray = Array.from(countriesMap, ([key, value]) => ({
  value: key,
  label: value,
}));
